#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }
use Mojolicious::Commands;

binmode STDOUT, ":utf8";
binmode STDERR, ":utf8";

# Start command line interface for application
Mojolicious::Commands->start_app('CrudExample');
